# Generated by Django 4.2.8 on 2023-12-10 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=127, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=127, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=127, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='like_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='like_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='like_functionality',
            field=models.BooleanField(default=False),
        ),
    ]
